# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e72d4d626aed3c5ff5796f8d8b0d6b247bb78c7e99b835279a1cf1a508bb78093dffffa13c95a4b3b9472a16c29ab83938a5f0371cc4d343d4ecddd29930ca2

test:
  secret_key_base: 4bac162141a89e57c222b2ae46c2db1249e34e22aa3a08f6e5b8aaee5bf09a9ea08d0ba00f049cda177005104224bd3187fcda2a09182a9f1df51264ffd4ff1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
